### ISSUE TITLE
Error  GannetLoad (line 914) 

### ISSUE THREAD

**Issue by grjd** [richardedden/Gannet3.1#1]
Hi,
I got this error message when trying to call GannetLoad.
Any help is more than welcome.

Thank you!
Jaime

```
MRS_struct = GannetLoad({'P19456.7'});
Warning: ********** An error occured while loading dataset: 'P19456.7'. Check data. Skipping to next dataset in batch
********** 
> In GannetLoad (line 914) 


********** ERROR REPORT **********

Filename: P19456.7

Error using optimset (line 163)
No default options available for the function 'lsqcurvefit'.

Error in FitChoCr (line 8)
lsqopts = optimset('lsqcurvefit');

Error in PhaseCorrection (line 93)
ModelParamChoCr = FitChoCr(freq(freqLim), SUM_ChoCr, x0, MRS_struct.p.LarmorFreq(ii));

Error in GannetLoad (line 416)
            MRS_struct.fids.data = PhaseCorrection(MRS_struct.fids.data, MRS_struct);
```

**Comment by grjd** [comment]
The previous error message is gone when Optimize Toolbox is installed.
But now I get this:
```

>> MRS_struct = GannetLoad({'P19456.7'});

Unstable residual water detected. Applying residual water filter to transient: 1

Warning: ********** An error occured while loading dataset: 'P19456.7'. Check data. Skipping to next dataset in batch
********** 
> In GannetLoad (line 914) 


********** ERROR REPORT **********

Filename: P19456.7

Undefined function 'hilbert' for input arguments of type 'double'.

Error in SignalFilter>BaselineModeling (line 89)
z.imag = -imag(hilbert(z.real));

Error in SignalFilter (line 10)
z = BaselineModeling(in, lipid_flag, water_flag, MRS_struct);

Error in Robust_Spectral_Registration (line 87)
        DataToAlign(:,jj) = SignalFilter(spec(:,jj), lipid_flag, water_flag, MRS_struct);

Error in GannetLoad (line 475)
                    [AllFramesFTrealign, MRS_struct] = Robust_Spectral_Registration(MRS_struct);
```

**Comment by schorschinho** [comment]
Hi Jaime, 

You need to install the Signal Processing Toolbox as well to be able to calculate the Hilbert transform (https://www.mathworks.com/help/signal/ref/hilbert.html).

If you don't have that toolbox, you can change the spectral registration routine in GannetPreInitialise from 'RobustSpecReg' to 'SpecReg' - that routine does not require the 'hilbert' function.

Best,
Georg

**Comment by grjd** [comment]
Hi Georg,
I got SPT and that fixed that issue, but still, there is something wrong.
Attached the pdfs of GannetLoad, using either SpecReg and RobustSpecReg. 
As you can see is not right (Volume 0 mL).
I am using Gannet 3.1 and  Matlab '9.7.0.1261785 (R2019b) Update 3' in a Mac OS Mojave.

[Load80-noH.pdf](https://github.com/richardedden/Gannet3.1/files/4090055/Load80-noH.pdf)
[Load80.pdf](https://github.com/richardedden/Gannet3.1/files/4090056/Load80.pdf)


Also as a side note when I use SpecReg (not RobustSpecReg) I got this warning even though it finishes.

```
>> MRS_struct = GannetLoad({'P19456.7'});
Spectral registration - Fitting transient: 1Warning: Iteration limit exceeded.  Returning results from final iteration. 
> In nlinfit (line 320)
  In Spectral_Regist
Spectral registration - Fitting transient: 2Warning: Iteration limit exceeded.  Returning results from final iteration. 
> In nlinfit (line 320)
...
```

**Comment by richardedden** [comment]
What GE sequence are you using? It might not be pulling the header info
correctly?

Richard

**Comment by markmikkelsen** [comment]
If you could send us your file, we can figure out what's going on.


Mark
