### ISSUE TITLE
Error GannetLoad GE P file

### ISSUE THREAD

**Issue by grjd** [richardedden/Gannet3.1#3]
Hi 
I am getting this error message when I call GannetLoad
I share the P file from GE [here](https://mega.nz/file/NoJ2BBKJ#19UnBbawCQx3_O13JIvOnooKi0uXjqIUWvUVdHF-E98)
Thanks,
Jaime
 
>> MRS = GannetLoad({'P03072.7'});

Robust spectral registration - Iteration: 128
Robust spectral registration - Iteration: 128

Performing weighted averaging of subspectra...

Filtering out residual water signal...

Warning: ********** An error occured while loading dataset:
'P03072.7'. Check data. Skipping to next dataset in batch ********** 
> In GannetLoad (line 920) 
Warning: Control Character '\P' is not valid. See 'doc sprintf' for
control characters valid in the format string. 
> In GannetLoad (line 921) 

********** ERROR REPORT **********

Filename:    P03072.7

Error using set
Value must be a handle

Error in <a href="matlab:matlab.internal.language.introspective.errorDocCallback('GannetPlotPrePostAlign', 'C:

**Comment by markmikkelsen** [comment]
Hi Jaime,

I was able to run your data with no issues. See attached.

Which version of MATLAB are you using? And are you on Windows, Linux, or macOS?

It's also worth checking you have all the [necessary](https://markmikkelsen.github.io/Gannet-docs/index.html#installation) MATLAB toolboxes installed.


Mark

**Comment by grjd** [comment]
Hi Mark,

I am running Matlab 2015a on Windowx 10.
I set the path as in the instructions again but got the same ERROR
See results of "ver" command for Matlan version and toolboxes

>> addpath(genpath('C:\Program Files\MATLAB\MATLAB Production Server\R2015a\toolbox\Gannet3.1-master'));
>> savepath 
>> MRS = GannetLoad({'P03072.7'});

Robust spectral registration - Iteration: 128
Robust spectral registration - Iteration: 128

Performing weighted averaging of subspectra...

Filtering out residual water signal...

Warning: ********** An error occured while loading dataset:
'P03072.7'. Check data. Skipping to next dataset in batch ********** 
> In GannetLoad (line 920) 
Warning: Control Character '\P' is not valid. See 'doc sprintf' for
control characters valid in the format string. 
> In GannetLoad (line 921) 


********** ERROR REPORT **********

Filename: P03072.7

Error using set
Value must be a handle

Error in <a href="matlab:matlab.internal.language.introspective.errorDocCallback('GannetPlotPrePostAlign', 'C:
=================================================================
>> ver
----------------------------------------------------------------------------------------------------
MATLAB Version: 8.5.0.197613 (R2015a)
MATLAB License Number: 161052
Operating System: Microsoft Windows 10 Pro Version 10.0 (Build 18363)
Java Version: Java 1.7.0_60-b19 with Oracle Corporation Java HotSpot(TM) 64-Bit Server VM mixed mode
----------------------------------------------------------------------------------------------------
MATLAB                                                Version 8.5        (R2015a)
Simulink                                              Version 8.5        (R2015a)
Aerospace Blockset                                    Version 3.15       (R2015a)
Aerospace Toolbox                                     Version 2.15       (R2015a)
Antenna Toolbox                                       Version 1.0        (R2015a)
Bioinformatics Toolbox                                Version 4.5.1      (R2015a)
Communications System Toolbox                         Version 6.0        (R2015a)
Computer Vision System Toolbox                        Version 6.2        (R2015a)
Control System Toolbox                                Version 9.9        (R2015a)
Curve Fitting Toolbox                                 Version 3.5.1      (R2015a)
DO Qualification Kit                                  Version 2.5        (R2015a)
DSP System Toolbox                                    Version 9.0        (R2015a)
Data Acquisition Toolbox                              Version 3.7        (R2015a)
Database Toolbox                                      Version 5.2.1      (R2015a)
Datafeed Toolbox                                      Version 5.1        (R2015a)
EEGLAB Toolbox to process EEG data                    Version -          see     
Econometrics Toolbox                                  Version 3.2        (R2015a)
Embedded Coder                                        Version 6.8        (R2015a)
Filter Design HDL Coder                               Version 2.9.7      (R2015a)
Financial Instruments Toolbox                         Version 2.1        (R2015a)
Financial Toolbox                                     Version 5.5        (R2015a)
Fixed-Point Designer                                  Version 5.0        (R2015a)
Fuzzy Logic Toolbox                                   Version 2.2.21     (R2015a)
Global Optimization Toolbox                           Version 3.3.1      (R2015a)
HDL Coder                                             Version 3.6        (R2015a)
HDL Verifier                                          Version 4.6        (R2015a)
IEC Certification Kit                                 Version 3.5        (R2015a)
Image Acquisition Toolbox                             Version 4.9        (R2015a)
Image Processing Toolbox                              Version 9.2        (R2015a)
Instrument Control Toolbox                            Version 3.7        (R2015a)
LTE System Toolbox                                    Version 2.0        (R2015a)
MATLAB Coder                                          Version 2.8        (R2015a)
MATLAB Compiler                                       Version 6.0        (R2015a)
MATLAB Compiler SDK                                   Version 6.0        (R2015a)
MATLAB Distributed Computing Server                   Version 6.6        (R2015a)
MATLAB Report Generator                               Version 4.1        (R2015a)
Mapping Toolbox                                       Version 4.1        (R2015a)
Model Predictive Control Toolbox                      Version 5.0.1      (R2015a)
Model-Based Calibration Toolbox                       Version 4.8.1      (R2015a)
Neural Network Toolbox                                Version 8.3        (R2015a)
OPC Toolbox                                           Version 3.3.3      (R2015a)
Optimization Toolbox                                  Version 7.2        (R2015a)
Parallel Computing Toolbox                            Version 6.6        (R2015a)
Partial Differential Equation Toolbox                 Version 2.0        (R2015a)
Phased Array System Toolbox                           Version 3.0        (R2015a)
Polyspace Bug Finder                                  Version 1.3        (R2015a)
Polyspace Code Prover                                 Version 9.3        (R2015a)
RF Toolbox                                            Version 2.16       (R2015a)
Robotics System Toolbox                               Version 1.0        (R2015a)
Robust Control Toolbox                                Version 5.3        (R2015a)
Signal Processing Toolbox                             Version 7.0        (R2015a)
SimBiology                                            Version 5.2        (R2015a)
SimDriveline                                          Version 2.8        (R2015a)
SimElectronics                                        Version 2.7        (R2015a)
SimEvents                                             Version 4.4        (R2015a)
SimHydraulics                                         Version 1.16       (R2015a)
SimMechanics                                          Version 4.6        (R2015a)
SimPowerSystems                                       Version 6.3        (R2015a)
SimRF                                                 Version 4.4        (R2015a)
Simscape                                              Version 3.13       (R2015a)
Simulink 3D Animation                                 Version 7.3        (R2015a)
Simulink Code Inspector                               Version 2.3        (R2015a)
Simulink Coder                                        Version 8.8        (R2015a)
Simulink Control Design                               Version 4.2        (R2015a)
Simulink Design Optimization                          Version 2.7        (R2015a)
Simulink Design Verifier                              Version 2.8        (R2015a)
Simulink Desktop Real-Time                            Version 5.0        (R2015a)
Simulink PLC Coder                                    Version 1.9        (R2015a)
Simulink Real-Time                                    Version 6.2        (R2015a)
Simulink Report Generator                             Version 4.1        (R2015a)
Simulink Test                                         Version 1.0        (R2015a)
Simulink Verification and Validation                  Version 3.9        (R2015a)
Spreadsheet Link EX                                   Version 3.2.3      (R2015a)
Stateflow                                             Version 8.5        (R2015a)
Statistical Parametric Mapping                        Version 7771       (SPM12) 
Statistics and Machine Learning Toolbox               Version 10.0       (R2015a)
Symbolic Math Toolbox                                 Version 6.2        (R2015a)
System Identification Toolbox                         Version 9.2        (R2015a)
SystemTest                                            Version 2.6.9      (R2015a)
Trading Toolbox                                       Version 2.2        (R2015a)
Vehicle Network Toolbox                               Version 2.4        (R2015a)
Vision HDL Toolbox                                    Version 1.0        (R2015a)
Wavelet Toolbox                                       Version 4.14.1

**Comment by markmikkelsen** [comment]
This is likely an issue with R2015a. The earliest release of MATLAB I've tested v3.1 of Gannet with is R2016a on macOS Catalina.

Try typing `dbstop error` in the Command Window and then rerunning your data. Please let me know in which .m file and on which line of code the debugger stops. (You can type `dbclear all` to stop the debugger stopping at errors.)

**Comment by grjd** [comment]
Hi Mark
This is what I got


>> dbstop error
>> GannetLoad({'P03072.7'})

Robust spectral registration - Iteration: 128
Robust spectral registration - Iteration: 128

Performing weighted averaging of subspectra...

Filtering out residual water signal...

Warning: ********** An error occured while loading dataset:
'P03072.7'. Check data. Skipping to next dataset in batch ********** 
> In GannetLoad (line 920) 
Warning: Control Character '\P' is not valid. See 'doc sprintf' for
control characters valid in the format string. 
> In GannetLoad (line 921) 


********** ERROR REPORT **********

Filename: P03072.7

Error using set
Value must be a handle

Error in <a href="matlab:matlab.internal.language.introspective.errorDocCallback('GannetPlotPrePostAlign', 'C:


ans = 

      version: [1x1 struct]
            p: [1x1 struct]
           ii: 1
    metabfile: {'P03072.7'}
         fids: [1x1 struct]
         spec: [1x1 struct]
          out: [1x1 struct]

**Comment by markmikkelsen** [comment]
Did not the Editor pop up and show you where the error occurs in a particular .m file?

**Comment by grjd** [comment]
Thanks, Mark,
I debug the GannetLoad file and I found that the error is in line 417
MRS_struct.fids.data = PhaseCorrection(MRS_struct.fids.data, MRS_struct);
I will try to install those libraries and let you know (I don't these libraries anymore because I installed 2020b) //Wishing a Python Gannet...

'nanmean' requires one of the following:
  Financial Toolbox
  Statistics and Machine Learning Toolbox

Error in PhaseCorrection (line 58)
        d = nanmean(D);

**Comment by grjd** [comment]
Hi Mark,
The 2020b with the Financial Toolbox made it! I run the sequences Load and Fit and got no error!
I attach the spectra I got, could please let me know if they are ok?
Thank you very much for your help.

![fit_untitled](https://user-images.githubusercontent.com/7142903/109984733-5c7d7880-7d04-11eb-9783-e96e6527332e.png)

.
![GLoad_untitled](https://user-images.githubusercontent.com/7142903/109984533-293ae980-7d04-11eb-8918-52c14ec94f77.png)

**Comment by markmikkelsen** [comment]
Great! That looks all good to me.
